---
title: "Projects"
---

## NeutRal Milk Hotel
Neutral Milk Hotel is one of the most surreal and enigmatic artists in the history of music. I am, myself, a huge fan of the band, and thought it would be a cool project to analyze the intricacies of their music using data science.

This is a data-driven process to analyze and visualize different aspects of Neutral Milk Hotel’s discography. I used a *lot* of R libraries, a fair amount of APIs and webscraping, and also a little JavaScript.

Check out the results [here](results-only.html).
Check out the full project (with code and everything) [here](neutral-milk-hotel.html).

## Chronic Kidney Disease Prediction Model
I created a prediction model trained on a dataset, containing attributes of a person’s biological information and health based on medical tests to determine if a new patient is likely to have, or, in the future, develop Chronic Kidney Disease.

I used data science libraries like tidyverse, ggplot2, etc. to read, clean and wrangle, analyze and visualize data, and summarize and visualize classification analysis, and trained the model with the health records for patients with and without CKD, the model accurately (well over 98% of the time) predicted whether a ‘new’ patient has Chronic Kidney Disease or not.

Check out the Jupyter Notebook here [here](https://github.com/akshatthakur/chronic-kidney-disease/blob/main/ckd%20(1).ipynb).

## Hotel Databse
I created a SQL database from scratch, implementing functionality for complex and nested queries, and used ER Diagrams, UML diagrams, Relational Schemas, Normalization to plan and create the best possible product.

I stored relational schema in Oracle RDBMS, interfaced with JDBC SQL statements, and designed the GUI using JQuery and Swing.

Check out the [Github repo](https://github.com/akshatthakur/hotel-database).

***

More to come soon!
